// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0PMzHCgk09oeZSnNNfKbF7XQloesxYE',
    appId: '1:183325267149:web:b9a96e1fa22d54f863c584',
    messagingSenderId: '183325267149',
    projectId: 'real-reddit',
    authDomain: 'real-reddit.firebaseapp.com',
    storageBucket: 'real-reddit.appspot.com',
    measurementId: 'G-KL08SDXBJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmawWtiLzBJJFM2D1MLCEicrPuHXICXyQ',
    appId: '1:183325267149:android:b336be2d9d27031463c584',
    messagingSenderId: '183325267149',
    projectId: 'real-reddit',
    storageBucket: 'real-reddit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRoEl4EBKjXrpbr_095Jl_IpC_imLGwA',
    appId: '1:183325267149:ios:fb84f154160528c963c584',
    messagingSenderId: '183325267149',
    projectId: 'real-reddit',
    storageBucket: 'real-reddit.appspot.com',
    iosClientId: '183325267149-h9diuq5g6eafe7jfl1ls1v2kfc78c8fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.realReddit',
  );
}
